
name: Add Docker Labels and Build

on:
  push:
    branches: [ main ]

jobs:
  label-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Read metadata file
        id: readmeta
        run: |
          echo "VERSION=$(jq -r '.version' metadata.json)" >> $GITHUB_OUTPUT
          echo "COMMIT=$(jq -r '.commit' metadata.json)" >> $GITHUB_OUTPUT
          echo "REPO=$(jq -r '.repo' metadata.json)" >> $GITHUB_OUTPUT
          echo "DESC=$(jq -r '.description' metadata.json)" >> $GITHUB_OUTPUT

      - name: Create labels string
        id: make_labels
        run: |
          echo "labels=org.opencontainers.image.version=${{ steps.readmeta.outputs.VERSION }},org.opencontainers.image.revision=${{ steps.readmeta.outputs.COMMIT }},org.opencontainers.image.source=${{ steps.readmeta.outputs.REPO }},org.opencontainers.image.description=\"${{ steps.readmeta.outputs.DESC }}\"" >> $GITHUB_OUTPUT

      - name: Build image with labels (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          labels: ${{ steps.make_labels.outputs.labels }}
