name: CentOS

on:
- push
- pull_request

jobs:
  build:
    name: ${{ matrix.os }} build

    runs-on: ubuntu-18.04
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - centos:7
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        yum install -y epel-release
        yum install -y wget gawk
        yum install -y $(cat .github/workflows/yum.txt)
    - name: Install conda
      run: |
        wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
        chmod u+x Anaconda3-2020.02-Linux-x86_64.sh
        ./Anaconda3-2020.02-Linux-x86_64.sh -b
    - name: Set variables with conda executable and activate
      run: |
        echo "CONDA=/github/home/anaconda3/bin/conda" >> $GITHUB_ENV
        echo "CONDA_ACTIVATE=/github/home/anaconda3/bin/activate" >> $GITHUB_ENV
    - name: Get GRASS GIS runtime conda dependencies
      run: |
        source $CONDA_ACTIVATE
        $CONDA install -y -c anaconda numpy wxpython python-dateutil ply termcolor
    - name: Create installation directory
      run: |
        mkdir $HOME/install
    - name: Set number of cores for compilation
      run: |
        echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
    - name: Set LD_LIBRARY_PATH for compilation
      run: |
        echo "LD_LIBRARY_PATH=$HOME/install/lib" >> $GITHUB_ENV
    - name: Build
      run: |
        source $CONDA_ACTIVATE
        .github/workflows/build_centos.sh $HOME/install
    - name: Add the bin directory to PATH
      run: |
        echo "$HOME/install/bin" >> $GITHUB_PATH
    - name: Test executing of the grass command
      run: |
        source $CONDA_ACTIVATE
        .github/workflows/test_simple.sh
