---
name: ClangFormat Check
on:
  push:
    branches:
      - main
      - releasebranch_*
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_protected != true }}
permissions: {}
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: DoozyX/clang-format-lint-action@c71d0bf4e21876ebec3e5647491186f8797fde31 # v0.18.2
        with:
          source: "."
          clangFormatVersion: 15
          inplace: True
      - name: Create and uploads code suggestions to apply
        id: diff
        uses: ./.github/actions/create-upload-suggestions
        with:
          tool-name: clang-format
          # To keep repo's file structure in formatted changes artifact
          extra-upload-changes: .clang-format
