---
name: Create or check a release draft

on:
  push:
    branches:
      - main
      - releasebranch_*
    tags:
      - '**'
  pull_request:
    paths:
      - .github/**
      - utils/**

env:
  OUT_DIR: ${{ github.workspace }}/../grass_outdir
  GRASS: grass-${{ github.ref_name }}
permissions: {}
jobs:
  build:
    name: Package and create release draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checks-out repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11'
      - name: Create output directory
        run: |
          mkdir ${{ env.OUT_DIR }}
      - name: Generate ChangeLog file
        run: |
          python utils/gitlog2changelog.py
          mv ChangeLog ${{ env.OUT_DIR }}/ChangeLog
          gzip ${{ env.OUT_DIR }}/ChangeLog
      - name: Generate Git derived data files
        run: |
          echo "Generate VERSION_GIT file:"
          ./utils/generate_version_git_file.sh
          cat include/VERSION_GIT
          echo "Generate GENERATE_LAST_COMMIT_FILE:"
          python utils/generate_last_commit_file.py .
          cat core_modules_with_last_commit.json
          echo "Create core modules patch file:"
          git add core_modules_with_last_commit.json
          git diff --cached > \
            ${{ env.OUT_DIR }}/core_modules_with_last_commit.patch
      - name: Create tarballs (for tags only)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ..
          tar -cvf ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar \
            --exclude=".gi*" --exclude=".tr*" \
            --transform s/grass/${{ env.GRASS }}/ grass
          cd ${{ env.OUT_DIR }}
          gzip -9k ${{ env.GRASS }}.tar
          md5sum ${{ env.GRASS }}.tar.gz > ${{ env.GRASS }}.tar.gz.md5
          sha256sum ${{ env.GRASS }}.tar.gz > ${{ env.GRASS }}.tar.gz.sha256
          xz -9e ${{ env.GRASS }}.tar
          md5sum ${{ env.GRASS }}.tar.xz > ${{ env.GRASS }}.tar.xz.md5
          sha256sum ${{ env.GRASS }}.tar.xz > ${{ env.GRASS }}.tar.xz.sha256
      - name: Publish draft distribution to GitHub (for tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          name: GRASS GIS ${{ github.ref_name }}
          body: |
            Overview of changes
            - First change
            - Second change
          draft: true
          prerelease: ${{ contains(github.ref, 'RC') }}
          files: |
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.gz
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.gz.md5
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.gz.sha256
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.xz
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.xz.md5
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.xz.sha256
              ${{ env.OUT_DIR }}/ChangeLog.gz
              ${{ env.OUT_DIR }}/core_modules_with_last_commit.patch
