---
name: General linting

on:
  push:
    branches:
      - main
      - releasebranch_*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  super-linter:
    name: GitHub Super Linter

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false
      - name: Lint code base
        uses: super-linter/super-linter/slim@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # By default, super-linter expect all linters to have their config
          # files inside .github/linters.
          # Setting it to the root of the repo for easier configuration here.
          LINTER_RULES_PATH: .
          # Listed but commented out linters would be nice to have.
          # (see https://github.com/github/super-linter#environment-variables)
          #
          # Python (supported using Pylint) and C/C++ (not supported) are
          # handled separately due to the complexity of the settings.
          # VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          # VALIDATE_CSS: true
          # VALIDATE_DOCKER: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          # VALIDATE_GITHUB_ACTIONS_ZIZMOR: true  # handled in pre-commit
          VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          # VALIDATE_XML: true
          VALIDATE_YAML: true
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          YAML_CONFIG_FILE: .yamllint
