---
name: Validate Titles

on:
  # zizmor: ignore[dangerous-triggers] Limits to maintained main branch, and avoids running PR code
  pull_request_target:
    branches:
      - main
    types:
      - edited
      # The following types are default for pull_request_target
      - opened
      - synchronize
      - reopened

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  validate-titles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repository (doesn't include the PR changes)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Call PR title validation function
        run: python utils/generate_release_notes.py check "${PR_TITLE}" "" ""
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
