---
name: Validate Titles

on:
  pull_request_target:
    types:
      - edited
      # The following types are default for pull_request_target
      - opened
      - synchronize
      - reopened

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  validate-titles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repository (doesn't include the PR changes)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Call PR title validation function
        run: python utils/generate_release_notes.py check "${PR_TITLE}" "" ""
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
